In [1]:
import os
import json
import pandas as pd

# Define the directory containing the JSON summary files
summary_dir = 'results'
data = []

# Loop through each file and extract relevant information
for filename in os.listdir(summary_dir):
    if filename.endswith('_summary.json'):
        filepath = os.path.join(summary_dir, filename)
        with open(filepath, 'r') as file:
            record = json.load(file)
            data.append({
                'Intersection': record.get('Intersection'),
                'Pre_Mean': record.get('Pre_Mean'),
                'Post_Mean': record.get('Post_Mean'),
                'Pre_Std': record.get('Pre_Std'),
                'Post_Std': record.get('Post_Std'),
                'Pre_SE': record.get('Pre_SE'),
                'Post_SE': record.get('Post_SE'),
                'Pre_85th': record.get('Pre_85th'),
                'Post_85th': record.get('Post_85th'),
                'Pre_95th': record.get('Pre_95th'),
                'Post_95th': record.get('Post_95th'),
                'Pre_Max_85th': record.get('Pre_Max_85th'),
                'Post_Max_85th': record.get('Post_Max_85th'),
                'T_Statistic': record.get('T_Statistic'),
                'P_Value': record.get('P_Value'),
                'Pre_Volume': record.get('Pre_Volume'),
                'Post_Volume': record.get('Post_Volume'),
                'Combined Volume': record.get('Combined Volume') or record.get('Combined_Volumne')
            })

# Convert to DataFrame
df = pd.DataFrame(data)
df.loc['Total'] = [''] * (df.shape[1] - 1) + [df.iloc[:, -1].sum()]
df['Type'] = 'Mini Roundabout'

cols = df.columns.tolist()
# Move 'Type' from its current position
cols.insert(1, cols.pop(cols.index('Type')))
df.loc['Total', 'Type'] = ''
df = df[cols]

# Display the DataFrame to the user
#import ace_tools as tools; tools.display_dataframe_to_user(name="Intersection Treatment Results", dataframe=df)

FileNotFoundError: [Errno 2] No such file or directory: 'results'

In [3]:
df.head(20)

,Intersection,Type,Pre_Mean,Post_Mean,Pre_Std,Post_Std,Pre_SE,Post_SE,Pre_85th,Post_85th,Pre_95th,Post_95th,Pre_Max_85th,Post_Max_85th,T_Statistic,P_Value,Pre_Volume,Post_Volume,Combined Volume
0,Michigan St: 16th and 18th St,Mini Roundabout,18.709116,17.15413,2.637326,1.668685,0.064421,0.040724,24.018533,21.921338,27.951029,25.05517,34.0,38.0,28.649775,0.0,192850,166866,359716
1,Baird St and Hart Ave,Mini Roundabout,12.674601,12.458786,2.317914,1.347013,0.082941,0.046504,12.748362,16.653796,15.369276,19.967798,34.0,26.0,4.116221,0.000045,72179,106856,179035
2,Baird St & Hart Ave,Mini Roundabout,12.674601,12.458786,2.317914,1.347013,0.082941,0.046504,12.748362,16.653796,15.369276,19.967798,34.0,26.0,4.116221,0.000045,72179,106856,179035
Total,,,,,,,,,,,,,,,,,,,717786

In [6]:
df.to_csv('MR_Table.csv', index = False)